### ISSUE TITLE
Fix PEP8 errors and refactor code

### ISSUE THREAD

**Issue by therealoggng** [therealoggng/youtubeconverter#2]
It is necessary to fix errors in the project that do not correspond to the PEP8 style. Refactor the code if necessary

**Comment by Zoxon470** [comment]
Can you assign it to me?

**Comment by therealoggng** [comment]
@Zoxon470 DONE MAN!!

**Comment by Zoxon470** [comment]
@therealoggng Thanks)

**Comment by Zoxon470** [comment]
I have sent pull request https://github.com/therealoggng/youtubeconverter/pull/3

**Comment by therealoggng** [comment]
Thank you Ahmed! You make a great job!!
